# Generated by Django 4.2.13 on 2024-06-12 03:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('knox', '0008_remove_authtoken_salt'),
    ]

    operations = [
        migrations.AddField(
            model_name='authtoken',
            name='data',
            field=models.JSONField(null=True),
        ),
    ]
